### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by dinogit** [mzyy94/daikin-homekit#1]
Just got a brand new Sensira and wanted to play a bit with options. But what ever I tried, I am getting same error msg:

[src/daikin.rs:49] resp.status() = 404
Error: http responded with non-200 status code: 404 Not Found

Pls help

**Comment by mzyy94** [comment]
Hello,
First, run compatibility check and paste the result please. 
https://github.com/mzyy94/daikin-homekit#compatibility

**Comment by dinogit** [comment]
Hi,

this is what I get: 

[src/daikin.rs:49] resp.status() = 404
❌ API endpoint: HTTP Request failed. - http responded with non-200 status code: 404 Not Found

My Wifi adapter is Onecta App adapter (hope this helps)

**Comment by dinogit** [comment]
Also when running discovery, it finds the proper device on that IP address

**Comment by mzyy94** [comment]
It seems that the device Sensira doesn't have new API endpoint. It has only [legacy one,](https://github.com/ael-code/daikin-control/wiki/API-System) I think.

This application can be used on devices with new API.

**Comment by dinogit** [comment]
Did a bit more digging and found that Daikin has removed their local API in newer products and newer Wifi modules. Thank you for pointing me in right direction.
