### ISSUE TITLE
Doesn't work with iOS16+

### ISSUE THREAD

**Issue by TobyOoO** [mzyy94/daikin-homekit#2]
iOS 16+ introduced a new version of Home app, and this homekit integration seems not workable with that.
The aircon says no response after adding them to Home app.

**Comment by mzyy94** [comment]
It was caused by hap-rs library with pairing ID issue (https://github.com/ewilken/hap-rs/issues/90).
I've replace it patched version. https://github.com/mzyy94/daikin-homekit/commit/df1954143273ba4767e29ae9a01a7a88b68c2fda Fetch master branch and re-build it, or get latest release please.

**Comment by mzyy94** [comment]
Note: Before running a new build, remove all pairing data from your config directory shown in startup logs.
<img width="1074" alt="スクリーンショット 2023-08-13 22 25 44" src="https://github.com/mzyy94/daikin-homekit/assets/2971112/3c8beb2e-f646-4dce-a24b-103f48d9974a">

**Comment by TobyOoO** [comment]
Thank you! I’ll try it and get back to you.

**Comment by TobyOoO** [comment]
It works! Thanks for your timely response.
