### ISSUE TITLE
Couldn't add accessory after remove it in home app

### ISSUE THREAD

**Issue by hank418** [mzyy94/daikin-homekit#4]
Couldn't add accessory after remove it in home app, even I restart the router and restart the computer which is running this application.

But it worked fine until I remove the accessory.

**Comment by mzyy94** [comment]
A function of accessory removing is sometimes broken. To reset pairing information, please delete config files. See https://github.com/mzyy94/daikin-homekit/issues/2#issuecomment-1676360550

**Comment by hank418** [comment]
Deleted the directory and wait some times, it shows up again.
But it stuck at connecting air conditioner in home app, and failed in final.

**Comment by hank418** [comment]
I finally add accessory success.
I turn my iphone connect wifi to 2.4G, and turn off ipv6 from computer which is running application.
Than HAP worked fine.

**Comment by mzyy94** [comment]
Good!!!
