### ISSUE TITLE
HTTP 404 when running daikin-homekit Cargo-run or Cargo-build

### ISSUE THREAD

**Issue by jmasarweh** [mzyy94/daikin-homekit#6]
When executing Step 3 - `$ cargo build --release ` fails with:

- src/dailin.rs:49 resp.status() = 404
- Error: http responded with non-200 status code: 404 Not Found.

Same error when executing `$ cargo run --example compatibility_check 192.1.1.XX`

on macOs Sonoma 14.0 / M1
homebrew
Latest rust/cargo.

**Comment by mzyy94** [comment]
Can you try with debug flag like `RUST_LOG=daikin_homekit=debug daikin-homekit` and paste whole log

**Comment by jmasarweh** [comment]
here you go:


[$ daikin-homekit % RUST_LOG=daikin_homekit=debug daikin-homekit
 [2023-10-24T11:27:17Z DEBUG daikin_homekit::discovery] discovering daikin device from [192.168.1.151:30000](http://192.168.1.151:30000/) to [192.168.1.255:30050](http://192.168.1.255:30050/)
 [2023-10-24T11:27:18Z INFO  daikin_homekit::discovery] found daikin device at [192.168.1.2](http://192.168.1.2/): Living Room
 [2023-10-24T11:27:18Z INFO  daikin_homekit] config file location: FileStorage { dir_path: "/Users/jamil/Library/Application Support/daikin-homekit" }
[src/[daikin.rs:49](http://daikin.rs:49/)] resp.status() = 404
Error: http responded with non-200 status code: 404 Not Found

**Comment by mzyy94** [comment]
> Seems like the ip range starts at 151. instead of 2, since 1 is assigned to the router usually....?

It doesn't matter I think. 404 error at first request shown in the log means that an API endpoint is unavailable.
Which model of daikin AC do you use? 
Try `cargo run --example discovery` and  look at the endpoint. And then, `curl -v` it and check the response.

**Comment by jmasarweh** [comment]
It is a BRP069C4x (2023 model). Curl -v seems to connect t the host on port 80, but there is no GET/ response on that endpoint /dsiot/multireq...
Seems like my unit's gateway is not compatible with calls outside of the Daikin App...?

**Comment by mzyy94** [comment]
> Seems like my unit's gateway is not compatible with calls outside of the Daikin App...?

I think so, too. I don't have some info about BRP069C4x but an issue cbrandlehner/homebridge-daikin-local#123 tells me that it has only cloud API ;)

**Comment by jmasarweh** [comment]
You're right, and thanks a lot for the support and assistance. Cheers!
